// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgi-IYadwjw--lcrgcpd0bWPOnoFMgPI',
    appId: '1:314091593623:web:37f2e77025d37196d7eed2',
    messagingSenderId: '314091593623',
    projectId: 'bc-final-project',
    authDomain: 'bc-final-project.firebaseapp.com',
    storageBucket: 'bc-final-project.appspot.com',
    measurementId: 'G-5MDHJKXL4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBam6IL7A2LFfdeSFbxf6Ii9wg6y4fh-W0',
    appId: '1:314091593623:android:f531086e883e0f26d7eed2',
    messagingSenderId: '314091593623',
    projectId: 'bc-final-project',
    storageBucket: 'bc-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLMW21SDXPFiNjvCgsRO4gDCmxP468vU4',
    appId: '1:314091593623:ios:d89505a0d3b2c909d7eed2',
    messagingSenderId: '314091593623',
    projectId: 'bc-final-project',
    storageBucket: 'bc-final-project.appspot.com',
    iosClientId: '314091593623-fme05of6hi6hael66hr3tdunbr2cm8qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bcFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLMW21SDXPFiNjvCgsRO4gDCmxP468vU4',
    appId: '1:314091593623:ios:d89505a0d3b2c909d7eed2',
    messagingSenderId: '314091593623',
    projectId: 'bc-final-project',
    storageBucket: 'bc-final-project.appspot.com',
    iosClientId: '314091593623-fme05of6hi6hael66hr3tdunbr2cm8qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bcFinalProject',
  );
}
